language: node_js
node_js:
  - node
  - stable
before_install:
  - sudo apt-get update
  - sudo apt-get install ghostscript poppler-utils -y
  - yarn install
script:
  - yarn test
notifications:
  email: false
